[package]
name = "prom-write"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus_remote_write = { version = "0.1.0", path = "../lib", features = ["parse", "compression", "http"] }

anyhow = { version = "1.0.75", features = ["backtrace"] }
ureq = { version = "2.8.0", default-features = false, features = ["tls", "rustls"] }
url = "2.4.1"
